### ISSUE TITLE
About anchor

### ISSUE THREAD

**Issue by rainofmine** [yhenon/pytorch-retinanet#11] opened 2018-07-25 02:23 UTC
when I change anchor ratios or scales in anchor.py, there will be something wrong like these:
The shape of the mask [275256] at index 0 does not match the shape of the indexed tensor [206442, 1] at index 0
The shape of the mask [249660] at index 0 does not match the shape of the indexed tensor [187245, 1] at index 0
The shape of the mask [192012] at index 0 does not match the shape of the indexed tensor [144009, 1] at index 0
The shape of the mask [236904] at index 0 does not match the shape of the indexed tensor [177678, 1] at index 0
The shape of the mask [236904] at index 0 does not match the shape of the indexed tensor [177678, 1] at index 0
Do you know what they mean? Thank you

**Comment by yhenon** [comment] 2018-07-25 02:34
Hi,

Can you post the code of the changes you made?

In particular, I think there might be issues if you changed the number of
scales or ratios

**Comment by rainofmine** [comment] 2018-07-25 02:56
Yes, I just changed the of scales or ratios in the __init__.  The error occurs.

**Comment by rainofmine** [comment] 2018-07-25 02:58
Yes, I just changed the scales or ratios in the init. The error occurs.

**Comment by yhenon** [comment] 2018-07-25 03:10
I'll need to look into this a little more tomorrow. In the meantime, I think it may be necessary to modify the `num_anchors` parameter in model.py (both in regression and classification model)

**Comment by yhenon** [comment] 2018-08-03 15:44
FYI I am planning on adding a config file indeed. I'm going to close this as the issue is resolved.

**Closed by yhenon** 2018-08-03 15:44 UTC
